"""Create meeting analysis table

Revision ID: 95f715ecbb5a
Revises: d60e6dbd15b8
Create Date: 2026-06-29 20:19:49.840231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95f715ecbb5a'
down_revision: Union[str, Sequence[str], None] = 'd60e6dbd15b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('minutes_of_meeting', sa.Text(), nullable=False),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decisions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sentiment', sa.String(length=30), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_analysis_id'), 'meeting_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_analysis_meeting_id'), 'meeting_analysis', ['meeting_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_analysis_meeting_id'), table_name='meeting_analysis')
    op.drop_index(op.f('ix_meeting_analysis_id'), table_name='meeting_analysis')
    op.drop_table('meeting_analysis')
    # ### end Alembic commands ###
