"""Create meetings table

Revision ID: d914d51abdf9
Revises: d9e475978f19
Create Date: 2026-06-27 19:19:22.340731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd914d51abdf9'
down_revision: Union[str, Sequence[str], None] = 'd9e475978f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_type', sa.Enum('BUSINESS', 'LECTURE', 'WEBINAR', 'WORKSHOP', 'INTERVIEW', 'PERSONAL', name='meetingtype'), nullable=False),
    sa.Column('recording_path', sa.String(length=1000), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.Enum('UPLOADED', 'PROCESSING', 'TRANSCRIBED', 'SUMMARIZED', 'COMPLETED', 'FAILED', name='meetingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_index(op.f('ix_meetings_user_id'), 'meetings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_user_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
